### PR TITLE
Produce warning if there are no valid manifests files in the paths

### PR DESCRIPTION
**Pull request by crisidev**
When running in the wrong directory, where there are no valid YAML manifests, nyl does not report to the user that it found 0 manifests and just exists clean.

This PR addresses this issue by adding a warning log that explains the user what's wrong.

### CODE REVIEW

**Review by ulucs — APPROVED** [review]

**Comment by crisidev** [comment]
There are some permission issues not related with my MR for `argocd-cmp` and `build`. I guess there are coming from the migration of the repo under `helsing-ai`?

**Comment by ulucs** [comment]
ah yes, we missed those changes during the migration

**Comment by NiklasRosenstein** [comment]
I merged develop into this branch after #53

edit: I spoke too soon. Despite "Maintainers are allowed to edit this pull request." I get

```
❯ g push
error: Authentication error: Authentication required: You must have push access to verify locks
error: failed to push some refs to 'github.com:crisidev/nyl.git'
```

**Comment by NiklasRosenstein** [comment]
This pull request includes an important change to the `load_manifests` function in the `src/nyl/commands/template.py` file. The change adds a warning log when no valid manifests are found in the specified paths.

* [`src/nyl/commands/template.py`](diffhunk://#diff-fd5e734e06e9c3227baf68d33377aef1febe8031f586823fca4144bf74c4b443R389-R394): Added a warning log to inform users when no valid manifests are found in the specified paths. This helps users understand that Nyl does not recursively enumerate directory contents and ensures they specify at least one path with valid YAML manifests.

**Review by NiklasRosenstein — APPROVED** [review]

**Comment by NiklasRosenstein** [comment]
Oh fun, I hit this every now and then and never do I remember what you need to do to fix it. Probably something got turned off during the move of the repository (I believe packages are User/Org scoped so something needs to be enabled there).

image

edit: Hm, the package exists and has recently tagged things there. I believe the issue is that @crisidev is not a collaborator on the repository. Then publishing fails because you wouldn't want a non-collaborator to be able to publish stuff directly into the Org's package registry.

image

**Comment by crisidev** [comment]
If I can be added to the org, I can just redo the PR from a branch and get over this.

**Comment by NiklasRosenstein** [comment]
Yes, that may be the easiest way forward. I don't know what's the usual way to handle this situation in GitHub actions. The REST API seems to have a `author_association` field that could be used to tell if the user is a collaborator or not, but that field is not accessible easily in actions from what I can see (though you could make an API call and .. but that turns ugly very quickly).

**Pull request closed without merging**
